### ISSUE TITLE
Install SULU Demo on Laravel Homestead

### ISSUE THREAD

**Issue by insystema** [sulu/sulu-demo#110]
Hi all!
I'm tring to install sulu-demo on Laravel Homestead VM
php version 8.1 according .php-version
elasticsearch version 7.9.0
sulu version 2.5.9

While executing the command:

    $ bin/console sulu:build dev

I get error:

    Build Targets
    =============
    +---+--------------------+------------------------------------------------------------------------------------------------+
    | # | Builder          | Deps                                                                                           |
    +---+--------------------+------------------------------------------------------------------------------------------------+
    | 0 | article_index |                                                                                                |
    | 1 | database       |                                                                                                |
    | 2 | phpcr             | database                                                                                       |
    | 3 | phpcr_migrations   | phpcr                                                                                          |
    | 4 | fixtures          | database, phpcr                                                                                |
    | 5 | user                | fixtures, database                                                                             |
    | 6 | system_collections | database, fixtures                                                                             |
    | 7 | security          | fixtures, database                                                                             |
    | 8 | dev                  | article_index, database, fixtures, phpcr, user, phpcr_migrations, system_collections, security |
    +---+--------------------+------------------------------------------------------------------------------------------------+
    
    Options:
    
      - nodeps: false
      - keep-exit-code: false
      - destroy: false
      - help: false
      - quiet: false
      - verbose: false
      - version: false
      - ansi: NULL
      - no-interaction: false
      - env: 'dev'
      - no-debug: false
    
    Look good? (y)
    
    Executing builders
    ==================
    
    Target: article_index
    
        Create index for "live" manager.
        
        In Connection.php line 693:
                                                                                                                                
          {"error":"Content-Type header [application/vnd.elasticsearch+json;compatible-with=7] is not supported","status":406}  
                                                                                                                                
        
        sulu:build [-D|--nodeps] [-k|--keep-exit-code] [--destroy] [--] [<target>]

How to fix this error?

Thanks

**Comment by alexander-schranz** [comment]
@insystema you are using a too old elasticsearch version. Like in the composer.json and in the docker-compose.yml defined you need atleast `7.17.*` or a newer `7.*` version: https://github.com/sulu/sulu-demo/blob/a1b2c187916d743de73b1fdad9b3dcf3298cbe48/docker-compose.yml#L20

**Comment by insystema** [comment]
Changed the version to 7.17.6 and it worked. Thank you.
