### ISSUE TITLE
Add sulu demo to packagist

### ISSUE THREAD

**Issue by Isarien** [sulu/sulu-demo#21]
I try to install the demo website with composer (php composer create-project sulu/sulu-demo). It did not work, and I have this message :

Could not find package sulu/sulu-demo with stability stable.

It seems it's because the package is not available on packagist.

**Comment by alexander-schranz** [comment]
Thank you for reporting currently its not in packegist you can just clone it and run composer install on it.

**Comment by chirimoya** [comment]
done

**Comment by rogoit** [comment]
This is still there ;(
