### ISSUE TITLE
Unable to login in admin

### ISSUE THREAD

**Issue by gram7gram** [sulu/sulu-demo#42]
On a fresh install with default user and roles an attempt to login as `admin` (with pass `admin`) keep redirecting me to login page.

From bottom to top: login page, successful login, admin index page, redirect to login.
![screenshot_2018-01-19_13-56-02](https://user-images.githubusercontent.com/8168799/35149888-82a8d9c6-fd20-11e7-95f2-b7d138bb46b1.png)

Profiler shows valid user token on login_check, but anonymous later.

`var` directory is freely writable/readable.

**Comment by alexander-schranz** [comment]
Hello @gram7gram,

please check the response content of the login. If it returns a PHP Warning the JSON is not valid and sulu can't then redirect correctly.

Example on PHP 5.6 this happens when in the php.ini `always_populate_raw_post_data` is not set to `-1`.

**Comment by alexander-schranz** [comment]
@gram7gram I'm also not sure if it works when you call it over `/admin.php` ... I think you need to configure your webserver correctly: http://docs.sulu.io/en/latest/cookbook/web-server/index.html. Or use the PHP internal webserver with `server:run`

**Comment by gram7gram** [comment]
@alexander-schranz, the response of `POST /admin.php/admin/login_check` is a valid json
```json
{"url":"/admin.php/admin/"}
```
To not waste time, I will create a fork with a use case.
Please, wait.

**Comment by alexander-schranz** [comment]
@gram7gram please try use the `server:run` command to use the php internal server to test if its `/admin.php/admin...` request which makes problem. Make also sure sessions are writeable and you didn't disable cookies for the session.

**Comment by gram7gram** [comment]
@alexander-schranz possible, but a bad practice.

I need close-to-production environment, so standalone server was used.

When you have time, please see [gram7gram/sulu-demo](https://github.com/gram7gram/sulu-demo)

**Comment by wachterjohannes** [comment]
@gram7gram I have taken a look at your environment - basically it looks quite well. but the problem I see is that you configure your vhost wrong. see our documentation for the correct vhost file http://docs.sulu.io/en/latest/cookbook/web-server/apache.html#virtual-host-configuration

**Comment by gram7gram** [comment]
This makes sense when `IfModule` is true, though module is not required.

To be fair, I enabled: `expires`, `deflate`, `rewrite` - still unable to login.

**Comment by wachterjohannes** [comment]
and you have set the root-directory to `/path/to/project/web`? you should not use `/admin.php` you should be able to call `/admin`

**Comment by gram7gram** [comment]
Miracle happened.

As you said, by opening `/admin` instead of `/admin.php/admin` (`rewrite` module becomes active) I was welcomed with dashboard!

**I am confused, but can accept it. Thank you!**

Issue can be closed, I suppose.

*Bottomline*
*Documentation or README should specify required modules for apache/nginx.*
*Or Docker container can encapsulate it.*

**Comment by wachterjohannes** [comment]
@gram7gram could you create a PR in the documentation?
