### ISSUE TITLE
Webspace "preview not available"

### ISSUE THREAD

**Issue by gram7gram** [sulu/sulu-demo#43]
After successful elasticsearch configuration and reinstalling application with:

`bin/adminconsole --env=dev app:install --destroy`

What should I add to elasticsearch to enable site live preview? 
After code review, I assumed it is a missing `teaser`-like index. If it is not an elastic issue, please instruct me.

![screenshot_2018-01-22_17-48-12](https://user-images.githubusercontent.com/8168799/35229601-7a73c440-ff9c-11e7-987a-c66d41b8f6c4.png)

Relevant trace

![screenshot_2018-01-22_18-03-54](https://user-images.githubusercontent.com/8168799/35230431-aae99c56-ff9e-11e7-99c3-cd6e9decc9b9.png)

`GET http://localhost:15300/admin/api/teasers?ids=article;7685578a-4a8b-4370-a727-6ffaa09d96af,content;7f25ae1f-e7d0-4ac2-90a7-a11d8cd88e8c&locale=de`

Also, does live preview corresponds to `ongr_elasticsearch.managers.live` section in `config.yml`?

**Comment by alexander-schranz** [comment]
@gram7gram not sure but for me it looks like wrong version of elasticsearch. You need to use a `5.*` Version as the [ongr bundle](https://github.com/ongr-io/ElasticsearchBundle) currently does not support the new `6.*` Version.

**Comment by wachterjohannes** [comment]
@gram7gram for massivesearch you have to set the version in the config:

```
massive_search:
    # ...
    adapters:
        elastic:
            version: 5.6
```

**Comment by gram7gram** [comment]
@wachterjohannes, thank you. It works!

Issue can be closed.
