### ISSUE TITLE
  Compile Error: Cannot use 'Object' as class name as it is reserved

### ISSUE THREAD

**Issue by rogoit** [sulu/sulu-demo#50]
After asset install cmd on PHP7.2

Fatal error: Cannot use 'Object' as class name as it is reserved in /Users/rocket/development/nevercodealone/cms/sulu/sulu-demo/vendor/ongr/elasticsearch-bundle/Annotation/Object.php on line 23

Call Stack:
    0.0004     390776   1. {main}() /Users/rocket/development/nevercodealone/cms/sulu/sulu-demo/bin/adminconsole:0
    0.0090    1258296   2. include('/Users/rocket/development/nevercodealone/cms/sulu/sulu-demo/bin/console.php') /Users/rocket/development/nevercodealone/cms/sulu/sulu-demo/bin/adminconsole:7
    0.0229    2383024   3. Symfony\Bundle\FrameworkBundle\Console\Application->run() /Users/rocket/development/nevercodealone/cms/sulu/sulu-demo/bin/console.php:23
    0.0386    2788928   4. Symfony\Bundle\FrameworkBundle\Console\Application->doRun() /Users/rocket/development/nevercodealone/cms/sulu/sulu-demo/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:148
    0.0386    2788928   5. AdminKernel->boot() /Users/rocket/development/nevercodealone/cms/sulu/sulu-demo/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:64
    0.0630    3586616   6. AdminKernel->initializeContainer() /Users/rocket/development/nevercodealone/cms/sulu/sulu-demo/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php:135
    0.2624   10277488   7. Symfony\Component\DependencyInjection\ContainerBuilder->compile() /Users/rocket/development/nevercodealone/cms/sulu/sulu-demo/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php:641
    0.2740   10281248   8. Symfony\Component\DependencyInjection\Compiler\Compiler->compile() /Users/rocket/development/nevercodealone/cms/sulu/sulu-demo/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ContainerBuilder.php:778
    1.7288   27419360   9. ONGR\ElasticsearchBundle\DependencyInjection\Compiler\MappingPass->process() /Users/rocket/development/nevercodealone/cms/sulu/sulu-demo/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/Compiler.php:141
    1.7288   27419360  10. Symfony\Component\DependencyInjection\ContainerBuilder->get() /Users/rocket/development/nevercodealone/cms/sulu/sulu-demo/vendor/ongr/elasticsearch-bundle/DependencyInjection/Compiler/MappingPass.php:32
    1.7288   27419360  11. Symfony\Component\DependencyInjection\ContainerBuilder->doGet() /Users/rocket/development/nevercodealone/cms/sulu/sulu-demo/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ContainerBuilder.php:588
    1.7289   27419384  12. Symfony\Component\DependencyInjection\ContainerBuilder->createService() /Users/rocket/development/nevercodealone/cms/sulu/sulu-demo/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ContainerBuilder.php:623
    1.7289   27419760  13. Symfony\Component\DependencyInjection\ContainerBuilder->doResolveServices() /Users/rocket/development/nevercodealone/cms/sulu/sulu-demo/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ContainerBuilder.php:1134
    1.7305   27443304  14. Symfony\Component\DependencyInjection\ContainerBuilder->doResolveServices() /Users/rocket/development/nevercodealone/cms/sulu/sulu-demo/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ContainerBuilder.php:1221
    1.7305   27443304  15. Symfony\Component\DependencyInjection\ContainerBuilder->doGet() /Users/rocket/development/nevercodealone/cms/sulu/sulu-demo/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ContainerBuilder.php:1264
    1.7305   27443304  16. Symfony\Component\DependencyInjection\ContainerBuilder->createService() /Users/rocket/development/nevercodealone/cms/sulu/sulu-demo/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ContainerBuilder.php:623
    1.7370   27945344  17. ReflectionClass->newInstanceArgs() /Users/rocket/development/nevercodealone/cms/sulu/sulu-demo/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ContainerBuilder.php:1159
    1.7370   27945536  18. ONGR\ElasticsearchBundle\Mapping\DocumentParser->__construct() /Users/rocket/development/nevercodealone/cms/sulu/sulu-demo/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ContainerBuilder.php:1159
    1.7370   27945536  19. ONGR\ElasticsearchBundle\Mapping\DocumentParser->registerAnnotations() /Users/rocket/development/nevercodealone/cms/sulu/sulu-demo/vendor/ongr/elasticsearch-bundle/Mapping/DocumentParser.php:81
    1.7376   27961456  20. Doctrine\Common\Annotations\AnnotationRegistry::registerFile() /Users/rocket/development/nevercodealone/cms/sulu/sulu-demo/vendor/ongr/elasticsearch-bundle/Mapping/DocumentParser.php:411

**Comment by alexander-schranz** [comment]
@rogoit the demo is currently not compatible with 7.2 because of a third party library ([ongr/elasticsearchbundle](https://github.com/sulu/suluarticlebundle#conflicts)) which has conflict.

**Comment by alexander-schranz** [comment]
This was an issue of a dependency and is now fixed.

**Comment by mathiaslacroix** [comment]
Same error after install _composer create-project sulu/sulu-demo_ with PHP 7_3 
----
PHP Fatal error:  Cannot use ONGR\ElasticsearchBundle\Annotation\Object as Object because 'Object' is a special class name in /Applications/MAMP/htdocs/sulu_demo2/vendor/sulu/article-bundle/Document/TagViewObject.php on line 14

Fatal error: Cannot use ONGR\ElasticsearchBundle\Annotation\Object as Object because 'Object' is a special class name in /Applications/MAMP/htdocs/sulu_demo2/vendor/sulu/article-bundle/Document/TagViewObject.php on line 14

In TagViewObject.php line 14:
                                                                               
  Compile Error: Cannot use ONGR\ElasticsearchBundle\Annotation\Object as Obj  
  ect because 'Object' is a special class name                                 
                                                                              
Script Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache handling the post-update-cmd event terminated with an exception
                                                                                                                                                      
  [RuntimeException]                                                                                                                                   
  An error occurred when executing the "'cache:clear --no-warmup'" command:                                                                                                                                                                                                                                   
                                                                                                                                                       
  Fatal error: Cannot use ONGR\ElasticsearchBundle\Annotation\Object as Object because 'Object' is a special class name in /Applications/MAMP/htdocs/  
  sulu_demo2/vendor/sulu/article-bundle/Document/TagViewObject.php on line 14                                                                                                                                                                                                                                 
                                                                                                                                                       
  PHP Fatal error:  Cannot use ONGR\ElasticsearchBundle\Annotation\Object as Object because 'Object' is a special class name in /Applications/MAMP/ht  
  docs/sulu_demo2/vendor/sulu/article-bundle/Document/TagViewObject.php on line 14                                                                     
                                                                                                                                                       
  In TagViewObject.php line 14:                                                                                                                        
                                                                                                                                                       
    Compile Error: Cannot use ONGR\ElasticsearchBundle\Annotation\Object as Obj                                                                        
    ect because 'Object' is a special class name   
----

**Comment by alexander-schranz** [comment]
@mathiaslacroix how did you install the demo? Which version of the `ongr/elasticsearch-bundle` is installed. Can try installing the demo the following way:

```bash
git clone git@github.com:sulu/sulu-demo.git
composer install
```

**Comment by mathiaslacroix** [comment]
Hello @alexander-schranz , thanks for your answer

For my first installation, I followed instructions of https://github.com/sulu/sulu-demo using 
`composer create-project sulu/sulu-demo`
and the error above was returned after
`bin/console sulu:build dev`
I also tried with ZIP with more problems

Following your answer I Installed Elasticsearch (I didn't know I needed to do it) with
`brew tap elastic/tap `
then 
`brew install elastic/tap/elasticsearch-full`

Following requirements I enabled Gd and Imagic in php.ini

then
`git clone git@github.com:sulu/sulu-demo.git` 
`bin/console sulu:build dev`
and not the same errors like above but only
`No alive nodes found in your cluster `
like following
> Executing builders
==================
Target: article_index
    
    In StaticNoPingConnectionPool.php line 53:
                                            
      No alive nodes found in your cluster  

I Googled about this error and tried issues about Elasticsearch and tried
`composer require ongr/elasticsearch-bundle "~6.0"`
I got diiferent errors about version problems with Elasticsearch looking like
`Problem 1- sulu/article-bundle 2.0.0 requires ongr/elasticsearch-bundle ^5.2 -> satisfiable by ongr/elasticsearch-bundle[5.2.x-dev, v5.2.0, v5.2.1, v5.2.2, v5.2.3, v5.2.4, v5.2.5, v5.2.6] but these conflict with your requirements or minimum-stability.`
so I tried other `composer require ongr/elasticsearch-bundle` with other versions start 5.2 without more result

- MacOs 10.15.4 - MAMP PHP-7.3.8 MySQL - 
I have local Symfony and Sulu skeleton applications already installed and functional on my MAMP

**Comment by alexander-schranz** [comment]
For the demo you need a running elasticsearch 5 or 6 instance. Think you run on 7 which currently does not work.

**Comment by alexander-schranz** [comment]
@mathiaslacroix the easiest way getting the services run is using the [docker-compose.yml](https://github.com/sulu/sulu-demo/blob/master/docker-compose.yml) provided in the demo sourcecode.

**Comment by alexander-schranz** [comment]
@mathiaslacroix If you want to use elasticsearch 6 you need run: `composer require elasticsearch/elasticsearch:^6.0` the bundle need to stay at 5.2.6.

**Comment by mathiaslacroix** [comment]
@alexander-schranz Thank you for answers
I will try that

**Comment by alexander-schranz** [comment]
@mathiaslacroix also feel free to join our slack channel for better support: https://sulu.io/services-and-support#chat
