### ISSUE TITLE
No template version 1.1

### ISSUE THREAD

**Issue by kfrohwein** [sulu/sulu-demo#53]
PHPStorm tells me there is no version 1.1 of the template and if I browse schemas.sulu.io I can't find it neither.

https://github.com/sulu/sulu-demo/blob/9c88a08e271c6d1bc9ab0adbda40d5ad61def576/app/Resources/templates/includes/blocks/heading.xml#L3

**Comment by Deltachaos** [comment]
I have the same problem

**Comment by alexander-schranz** [comment]
Thank you for your answers. The demo is still 1.6.6 and will be soon updated to sulu 2.0 were this will be fixed.
