### ISSUE TITLE
Documentation update

### ISSUE THREAD

**Issue by oprichnik** [sulu/sulu-demo#99]
It would be great to see in the docs: https://docs.sulu.io/en/2.4/cookbook/webpack-encore.html that after that the admin assets should be build like it's said here: https://docs.sulu.io/en/2.4/cookbook/build-admin-frontend.html

**Comment by alexander-schranz** [comment]
Not sure what you mean but if you miss something in the docs, we are happy to get a pull requeest the repository for the docs can be found [here](https://github.com/sulu/sulu-docs), current supported version which we improve the docs is 2.3: https://github.com/sulu/sulu-docs/tree/2.3

**Comment by alexander-schranz** [comment]
fixed via: sulu/sulu-docs#704
